services: 
  api: 
      build: .
      depends_on:
            - postgres
      ports:
            - 8000:8000
      env_file:
            - ./.env
      volumes:
        - ./:/usr/src/app:ro
      command: uvicorn app.main:app --host 127.0.0.1 --port 8000 --reload
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-db: 